version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: source/conf.py

python:
  install:
    - requirements: readthedocs/requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3"
