name: pythongis

channels:
  - conda-forge

dependencies:
  - python=3.12.12
  - myst-nb=1.4.0
  - git=2.55.0
  - jupyterlab=4.6.4
  - jupyterlab-git=0.54.1
  - jupyterlab-myst=2.7.0
  - contextily=1.7.1
  - dask=2026.8.0
  - dask-geopandas=0.5.0
  - datashader=0.19.1
  - folium=0.20.0
  - fiona=1.10.1
  - geocube=0.7.1
  - geodatasets=2026.5.1
  - geojson=3.3.0
  - geopandas=1.1.4
  - geoplot=0.5.1
  - geopy=2.5.0
  - hvplot=0.12.2
  - lonboard=0.16.0
  - matplotlib=3.11.2
  - matplotlib-scalebar=0.9.0
  - netcdf4=1.7.4
  - numpy=1.26.4
  - openjdk=25.0.2
  - openpyxl=3.1.5
  - osmnx=2.1.1
  - overturemaps=1.0.2
  - owslib=0.36.0
  - palettable=3.3.3
  - pandas=3.0.6
  - pyinterpolate=1.2.1
  - pyrosm=0.13.1
  - pysal=25.1
  - pysheds=0.5
  - rasterio=1.5.1
  - r5py=1.1.7
  - r5py.sampledata.helsinki>=0.1.1dev2
  - r5py.sampledata.sao_paulo>=0.1.1dev2
  - rasterstats=0.21.0
  - rioxarray=0.20.0
  - scipy=1.17.1
  - seaborn=0.13.2
  - shapely=2.1.2
  - xarray=2026.7.0
  - xarray_leaflet=0.2.3
  - xarray-spatial=0.10.18
  - xvec=0.5.2
  - zarr=3.1.5
